@startuml

'left to right direction

namespace "Сервис 1" as S1  {
object "Начисление бонусов\n за задания" as A1 {
   Начисление 1
   ---
   Начисление 2
   ---
   ...
}

}

namespace "Сервис 2" as S2  {
object "Начисление бонусов\n за покупки" as A2{
     Начисление 3
   ---
       Начисление 4
       ---
       ...
}
}


namespace "Композиция сущности" as S3  {
object "Начисление бонусов" as A3{
    Начисление 1
    ---
    Начисление 2
    ---
    Начисление 3
    ---
    Начисление 4
    ---
    ...
}
}

A1 --> A3
A2 --> A3

@enduml